### ISSUE TITLE
No error message shown on template errors

### ISSUE THREAD

**Issue by p2kmgcl** [metal/metal-soy-loader#4]
When I try to compile a project using `metal-soy-loader`, if the template has any error, an error object is thrown with this stack:

```
/tmp/metal-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:106
                        throw new Error("callback(): The callback was already called.");
                        ^

Error: callback(): The callback was already called.
    at context.callback (/tmp/metal-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:106:10)
    at SoyCompiler.<anonymous> (/tmp/metal-boilerplate/node_modules/metal-soy-loader/lib/index.js:59:4)
    at SoyCompiler.runListeners_ (/tmp/metal-boilerplate/node_modules/metal-events/lib/EventEmitter.js:463:15)
    at SoyCompiler.emit (/tmp/metal-boilerplate/node_modules/metal-events/lib/EventEmitter.js:189:9)
    at SoyCompiler.handleEnd_ (/tmp/metal-boilerplate/node_modules/metal-soy-loader/lib/SoyCompiler.js:149:9)
    at emitNone (events.js:105:13)
    at Stream.emit (events.js:207:7)
    at DestroyableTransform.handleEnd (/tmp/metal-boilerplate/node_modules/duplexer/index.js:81:21)
    at emitNone (events.js:110:20)
    at DestroyableTransform.emit (events.js:207:7)
    at endReadableNT (/tmp/metal-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:992:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

It would me more useful to show the compilation error, or at least capturing this error, as webpack-dev-server is stopped. I am going to investigate why this happens :)

**Comment by p2kmgcl** [comment]
Ok I think I know that is happening: when there is an error during the compilation, both "error" and "end" events are dispatched, which make sense, as the process reaches a termination.
The problem is that on `index.js` both events are being watched, so `loaderCallback` is called twice. I think this is easy to solve, so I am trying a PR

**Comment by Robert-Frampton** [comment]
https://github.com/metal/metal-soy-loader/pull/5
